version: 2.1

jobs:
  build-linux:
    docker:
      - image: cimg/base:2023.03

    steps:
      - checkout
      - run:
          name: "Install Cmake"
          command: sudo apt-get update && sudo apt-get install -y cmake
      - run:
          name: "Create build directory"
          command: mkdir build
      - run:
          name: "Build"
          command: cd build && cmake .. && make

workflows:
  build-linux-workflow:
    jobs:
      - build-linux
