version: 2.1

jobs:
  build-linux-gcc:
    docker:
      - image: iridescentrose/crosscraft-ci-linux-gcc:latest

    steps:
      - checkout
      - run:
          name: "Create build directory"
          command: mkdir build
      - run:
          name: "Build"
          command: cd build && cmake -DCMAKE_BUILD_TYPE=Release -GNinja .. && ninja
  build-linux-clang:
    docker:
      - image: iridescentrose/crosscraft-ci-linux-gcc:latest

    steps:
      - checkout
      - run:
          name: "Create build directory"
          command: mkdir build
      - run:
          name: "Build"
          command: cd build && cmake -DCMAKE_BUILD_TYPE=Release -GNinja ..  -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ && ninja

workflows:
  build-linux-workflow:
    jobs:
      - build-linux-gcc
      - build-linux-clang
